use_frameworks!

platform :ios, '10.0'

target 'NahimSecondPodLib_Example' do
  pod 'NahimSecondPodLib', :path => '../'

  target 'NahimSecondPodLib_Tests' do
    inherit! :search_paths

    
  end
end
